"""External connection contract. Board code has no ASM implementation dependency."""
from typing import Protocol, runtime_checkable

@runtime_checkable
class Backend(Protocol):
    def external_event(self, event: str, generation: int) -> None: ...
    def run(self, limit: int = 200000, stop: bytes = b'BOOT=OK\n') -> bool: ...
    def available_capabilities(self) -> frozenset[str]: ...
    def read_trace(self) -> list[dict]: ...
